classDiagram
    class EVENTS {
        <<enumeration>>
        PARAM_CHANGED
        PARAM_ADDED
        PARAM_REMOVED
        SHAPE_ADDED
        SHAPE_REMOVED
        SHAPE_MOVED
        SHAPE_SELECTED
        TAB_SWITCHED
        TAB_CREATED
        TAB_CLOSED
        SCENE_LOADED
        SCENE_SAVED
        VIEWPORT_CHANGED
        NODE_LINK_CREATED
        NODE_LINK_REMOVED
        NODE_MODULE_EDITED
        NODE_PARAM_CREATED
        NODE_EXPRESSION_CHANGED
    }